import React, { Component } from 'react';
import './App.css';
import UserTable from './view/UserTable'
import AddUserForm from './view/AddUserForm'
import EditUserForm from './view/EditUserForm'
import _ from "underscore"


class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      title: '',
      available: false,
      userId: null,
      userAction: "A",

data :[
  {title: "PHONE", value: 10, color: "red"},
  {title: "P", value: 60, color: "green"},
  {title: "C", value: 30, color: "#3da18d"},
  {title: "R", value: 20, color: "#69c2b0"},
  {title: "B", value: 10, color: "#a1d9ce"},
],
 input :  [
  { 
  id:1,
  name:"Fresh Atlantic Salmon",
  value:"10"
  },
  { 
  id:2,
  name:"crab2",
  value:"10"
  },
  { 
  id:3,
  name:"Fresh Atlantic Salmon",
  value:"10"
  },
  { 
  id:1,
  name:"crab",
  value:"10"
  },
  { 
  id:2,
  name:"crab2",
  value:"10"
  }
  ]


    }

  }

componentDidMount(){

let sample =  `[
  {
      "id": 7,
      "sequence_number": 7,
      "order_number": "FFOR1583217900346",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:45:00.346Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "f19a",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:45:00.347Z",
      "updatedAt": "2020-03-03T06:45:00.357Z",
      "orderItems": [
          {
              "id": 6,
              "product_cut_id": 176,
              "order_id": 7,
              "product_id": 50,
              "product_name": "Turkey",
              "date_placed": "2020-03-03T06:45:00.382Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 225,
              "rma_number": "1583217900382",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217900346-2",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:45:00.382Z",
              "updatedAt": "2020-03-03T06:45:00.382Z",
              "productCut": {
                  "id": 176,
                  "product_id": 50,
                  "product_variant_id": 59,
                  "cut_name": "Curry Cut (Medium Pieces)",
                  "units": "kg",
                  "price_per_unit": 450,
                  "pieces_per_unit": "19",
                  "no_of_serves": "20 - 25",
                  "description": null,
                  "is_default": true,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:20.837Z",
                  "updatedAt": "2020-03-03T04:39:20.837Z",
                  "productVariant": {
                      "id": 59,
                      "product_id": 50,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "PYFRPTK",
                      "total_quantity": 100,
                      "available_quantity": 30,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:16.124Z",
                      "updatedAt": "2020-03-03T04:39:16.124Z",
                      "product": {
                          "id": 50,
                          "sub_category_id": 4,
                          "name": "Turkey",
                          "colloquial_name": null,
                          "code": "PYFRPTK",
                          "min_price": 400,
                          "max_price": 420,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.5,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": true,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.776Z",
                          "updatedAt": "2020-03-03T04:39:15.776Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          },
          {
              "id": 5,
              "product_cut_id": 175,
              "order_id": 7,
              "product_id": 50,
              "product_name": "Turkey",
              "date_placed": "2020-03-03T06:45:00.370Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 210,
              "rma_number": "1583217900370",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217900346-1",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:45:00.370Z",
              "updatedAt": "2020-03-03T06:45:00.370Z",
              "productCut": {
                  "id": 175,
                  "product_id": 50,
                  "product_variant_id": 59,
                  "cut_name": "Whole Bird (Without Skin)",
                  "units": "kg",
                  "price_per_unit": 420,
                  "pieces_per_unit": "17",
                  "no_of_serves": "20 - 25",
                  "description": null,
                  "is_default": false,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:20.824Z",
                  "updatedAt": "2020-03-03T04:39:20.824Z",
                  "productVariant": {
                      "id": 59,
                      "product_id": 50,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "PYFRPTK",
                      "total_quantity": 100,
                      "available_quantity": 30,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:16.124Z",
                      "updatedAt": "2020-03-03T04:39:16.124Z",
                      "product": {
                          "id": 50,
                          "sub_category_id": 4,
                          "name": "Turkey",
                          "colloquial_name": null,
                          "code": "PYFRPTK",
                          "min_price": 400,
                          "max_price": 420,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.5,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": true,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.776Z",
                          "updatedAt": "2020-03-03T04:39:15.776Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          }
      ],
      "invoice": {
          "id": 2,
          "order_id": 7,
          "user_reward_ref": null,
          "invoice_number": "FFIN1583217900387",
          "invoice_date": "2020-03-02T18:30:00.000Z",
          "invoice_details": "Bought 2 Items from FreshFins",
          "delivery_fee": 0,
          "tax": 21.76,
          "subtotal": 435,
          "promocode": null,
          "discount_amount": 0,
          "total_price": 456.76,
          "mode_of_payment": "CASH",
          "gateway_ref": null,
          "transaction_id": null,
          "is_refund_requested": false,
          "refund_status": null,
          "reason_for_cancellation": null,
          "status": "PENDING",
          "createdAt": "2020-03-03T06:45:00.391Z",
          "updatedAt": "2020-03-03T06:45:00.391Z"
      },
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 9,
      "sequence_number": 9,
      "order_number": "FFOR1583217944238",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:45:44.239Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "9a77",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:45:44.239Z",
      "updatedAt": "2020-03-03T06:45:44.250Z",
      "orderItems": [
          {
              "id": 10,
              "product_cut_id": 7,
              "order_id": 9,
              "product_id": 5,
              "product_name": "Japenese Thread Fin Bream",
              "date_placed": "2020-03-03T06:45:44.271Z",
              "item_packed_by": null,
              "order_item_quantity": 1.5,
              "order_item_price": 450,
              "rma_number": "1583217944271",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217944238-2",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:45:44.271Z",
              "updatedAt": "2020-03-03T06:45:44.271Z",
              "productCut": {
                  "id": 7,
                  "product_id": 5,
                  "product_variant_id": 5,
                  "cut_name": "Cubes",
                  "units": "kg",
                  "price_per_unit": 300,
                  "pieces_per_unit": "18",
                  "no_of_serves": "18 - 20",
                  "description": null,
                  "is_default": false,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:16.238Z",
                  "updatedAt": "2020-03-03T04:39:16.238Z",
                  "productVariant": {
                      "id": 5,
                      "product_id": 5,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "SFSFHJT",
                      "total_quantity": 100,
                      "available_quantity": 65,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:15.829Z",
                      "updatedAt": "2020-03-03T04:39:15.829Z",
                      "product": {
                          "id": 5,
                          "sub_category_id": 1,
                          "name": "Japenese Thread Fin Bream",
                          "colloquial_name": "Sankara",
                          "code": "SFSFHJT",
                          "min_price": 280,
                          "max_price": 300,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.5,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": false,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.104Z",
                          "updatedAt": "2020-03-03T04:39:15.104Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          },
          {
              "id": 9,
              "product_cut_id": 6,
              "order_id": 9,
              "product_id": 5,
              "product_name": "Japenese Thread Fin Bream",
              "date_placed": "2020-03-03T06:45:44.263Z",
              "item_packed_by": null,
              "order_item_quantity": 2.5,
              "order_item_price": 700,
              "rma_number": "1583217944263",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217944238-1",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:45:44.263Z",
              "updatedAt": "2020-03-03T06:45:44.263Z",
              "productCut": {
                  "id": 6,
                  "product_id": 5,
                  "product_variant_id": 5,
                  "cut_name": "Whole Cleaned",
                  "units": "kg",
                  "price_per_unit": 280,
                  "pieces_per_unit": "18",
                  "no_of_serves": "18 - 20",
                  "description": null,
                  "is_default": true,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:16.229Z",
                  "updatedAt": "2020-03-03T04:39:16.229Z",
                  "productVariant": {
                      "id": 5,
                      "product_id": 5,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "SFSFHJT",
                      "total_quantity": 100,
                      "available_quantity": 65,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:15.829Z",
                      "updatedAt": "2020-03-03T04:39:15.829Z",
                      "product": {
                          "id": 5,
                          "sub_category_id": 1,
                          "name": "Japenese Thread Fin Bream",
                          "colloquial_name": "Sankara",
                          "code": "SFSFHJT",
                          "min_price": 280,
                          "max_price": 300,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.5,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": false,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.104Z",
                          "updatedAt": "2020-03-03T04:39:15.104Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          }
      ],
      "invoice": {
          "id": 4,
          "order_id": 9,
          "user_reward_ref": null,
          "invoice_number": "FFIN1583217944278",
          "invoice_date": "2020-03-02T18:30:00.000Z",
          "invoice_details": "Bought 2 Items from FreshFins",
          "delivery_fee": 0,
          "tax": 57.5,
          "subtotal": 1150,
          "promocode": null,
          "discount_amount": 0,
          "total_price": 1207.5,
          "mode_of_payment": "CASH",
          "gateway_ref": null,
          "transaction_id": null,
          "is_refund_requested": false,
          "refund_status": null,
          "reason_for_cancellation": null,
          "status": "PENDING",
          "createdAt": "2020-03-03T06:45:44.283Z",
          "updatedAt": "2020-03-03T06:45:44.283Z"
      },
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 3,
      "sequence_number": 3,
      "order_number": "FFOR1583217403018",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:36:43.018Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "f9f7",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:36:43.019Z",
      "updatedAt": "2020-03-03T06:36:43.040Z",
      "orderItems": [],
      "invoice": null,
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 1,
      "sequence_number": 1,
      "order_number": "FFOR1583211045431",
      "customer_ref": 8,
      "date_placed": "2020-03-03T04:50:45.432Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "8aad",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T04:50:45.434Z",
      "updatedAt": "2020-03-03T04:50:45.443Z",
      "orderItems": [],
      "invoice": null,
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 4,
      "sequence_number": 4,
      "order_number": "FFOR1583217515461",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:38:35.464Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "0b5f",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:38:35.466Z",
      "updatedAt": "2020-03-03T06:38:35.489Z",
      "orderItems": [],
      "invoice": null,
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 6,
      "sequence_number": 6,
      "order_number": "FFOR1583217873352",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:44:33.354Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "5f2e",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:44:33.356Z",
      "updatedAt": "2020-03-03T06:44:33.374Z",
      "orderItems": [
          {
              "id": 4,
              "product_cut_id": 48,
              "order_id": 6,
              "product_id": 18,
              "product_name": "Snapper / Mangrove Jack",
              "date_placed": "2020-03-03T06:44:33.419Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 215,
              "rma_number": "1583217873419",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217873352-4",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:44:33.419Z",
              "updatedAt": "2020-03-03T06:44:33.419Z",
              "productCut": {
                  "id": 48,
                  "product_id": 18,
                  "product_variant_id": 18,
                  "cut_name": "Cubes",
                  "units": "kg",
                  "price_per_unit": 430,
                  "pieces_per_unit": "12",
                  "no_of_serves": "18 - 20",
                  "description": null,
                  "is_default": false,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:16.726Z",
                  "updatedAt": "2020-03-03T04:39:16.726Z",
                  "productVariant": {
                      "id": 18,
                      "product_id": 18,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "SFSFHSP",
                      "total_quantity": 100,
                      "available_quantity": 72,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:15.897Z",
                      "updatedAt": "2020-03-03T04:39:15.897Z",
                      "product": {
                          "id": 18,
                          "sub_category_id": 1,
                          "name": "Snapper / Mangrove Jack",
                          "colloquial_name": "Seppili / Kendal",
                          "code": "SFSFHSP",
                          "min_price": 330,
                          "max_price": 430,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.8,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": true,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.347Z",
                          "updatedAt": "2020-03-03T04:39:15.347Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          },
          {
              "id": 3,
              "product_cut_id": 47,
              "order_id": 6,
              "product_id": 18,
              "product_name": "Snapper / Mangrove Jack",
              "date_placed": "2020-03-03T06:44:33.409Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 200,
              "rma_number": "1583217873409",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217873352-3",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:44:33.410Z",
              "updatedAt": "2020-03-03T06:44:33.410Z",
              "productCut": {
                  "id": 47,
                  "product_id": 18,
                  "product_variant_id": 18,
                  "cut_name": "Slices",
                  "units": "kg",
                  "price_per_unit": 400,
                  "pieces_per_unit": "10",
                  "no_of_serves": "20 - 25",
                  "description": null,
                  "is_default": false,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:16.695Z",
                  "updatedAt": "2020-03-03T04:39:16.695Z",
                  "productVariant": {
                      "id": 18,
                      "product_id": 18,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "SFSFHSP",
                      "total_quantity": 100,
                      "available_quantity": 72,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:15.897Z",
                      "updatedAt": "2020-03-03T04:39:15.897Z",
                      "product": {
                          "id": 18,
                          "sub_category_id": 1,
                          "name": "Snapper / Mangrove Jack",
                          "colloquial_name": "Seppili / Kendal",
                          "code": "SFSFHSP",
                          "min_price": 330,
                          "max_price": 430,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.8,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": true,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.347Z",
                          "updatedAt": "2020-03-03T04:39:15.347Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          },
          {
              "id": 2,
              "product_cut_id": 46,
              "order_id": 6,
              "product_id": 18,
              "product_name": "Snapper / Mangrove Jack",
              "date_placed": "2020-03-03T06:44:33.397Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 190,
              "rma_number": "1583217873397",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217873352-2",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:44:33.397Z",
              "updatedAt": "2020-03-03T06:44:33.397Z",
              "productCut": {
                  "id": 46,
                  "product_id": 18,
                  "product_variant_id": 18,
                  "cut_name": "Fillet",
                  "units": "kg",
                  "price_per_unit": 380,
                  "pieces_per_unit": "18",
                  "no_of_serves": "20 - 25",
                  "description": null,
                  "is_default": false,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:16.665Z",
                  "updatedAt": "2020-03-03T04:39:16.665Z",
                  "productVariant": {
                      "id": 18,
                      "product_id": 18,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "SFSFHSP",
                      "total_quantity": 100,
                      "available_quantity": 72,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:15.897Z",
                      "updatedAt": "2020-03-03T04:39:15.897Z",
                      "product": {
                          "id": 18,
                          "sub_category_id": 1,
                          "name": "Snapper / Mangrove Jack",
                          "colloquial_name": "Seppili / Kendal",
                          "code": "SFSFHSP",
                          "min_price": 330,
                          "max_price": 430,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.8,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": true,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.347Z",
                          "updatedAt": "2020-03-03T04:39:15.347Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          },
          {
              "id": 1,
              "product_cut_id": 45,
              "order_id": 6,
              "product_id": 18,
              "product_name": "Snapper / Mangrove Jack",
              "date_placed": "2020-03-03T06:44:33.381Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 175,
              "rma_number": "1583217873381",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217873352-1",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:44:33.382Z",
              "updatedAt": "2020-03-03T06:44:33.382Z",
              "productCut": {
                  "id": 45,
                  "product_id": 18,
                  "product_variant_id": 18,
                  "cut_name": "Whole Cleaned",
                  "units": "kg",
                  "price_per_unit": 350,
                  "pieces_per_unit": "18",
                  "no_of_serves": "15 - 20",
                  "description": null,
                  "is_default": true,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:16.656Z",
                  "updatedAt": "2020-03-03T04:39:16.656Z",
                  "productVariant": {
                      "id": 18,
                      "product_id": 18,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "SFSFHSP",
                      "total_quantity": 100,
                      "available_quantity": 72,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:15.897Z",
                      "updatedAt": "2020-03-03T04:39:15.897Z",
                      "product": {
                          "id": 18,
                          "sub_category_id": 1,
                          "name": "Snapper / Mangrove Jack",
                          "colloquial_name": "Seppili / Kendal",
                          "code": "SFSFHSP",
                          "min_price": 330,
                          "max_price": 430,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.8,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": true,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.347Z",
                          "updatedAt": "2020-03-03T04:39:15.347Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          }
      ],
      "invoice": {
          "id": 1,
          "order_id": 6,
          "user_reward_ref": null,
          "invoice_number": "FFIN1583217873425",
          "invoice_date": "2020-03-02T18:30:00.000Z",
          "invoice_details": "Bought 4 Items from FreshFins",
          "delivery_fee": 0,
          "tax": 39,
          "subtotal": 780,
          "promocode": null,
          "discount_amount": 0,
          "total_price": 819,
          "mode_of_payment": "CASH",
          "gateway_ref": null,
          "transaction_id": null,
          "is_refund_requested": false,
          "refund_status": null,
          "reason_for_cancellation": null,
          "status": "PENDING",
          "createdAt": "2020-03-03T06:44:33.432Z",
          "updatedAt": "2020-03-03T06:44:33.432Z"
      },
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 8,
      "sequence_number": 8,
      "order_number": "FFOR1583217926403",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:45:26.404Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "ec87",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:45:26.404Z",
      "updatedAt": "2020-03-03T06:45:26.414Z",
      "orderItems": [
          {
              "id": 8,
              "product_cut_id": 175,
              "order_id": 8,
              "product_id": 50,
              "product_name": "Turkey",
              "date_placed": "2020-03-03T06:45:26.438Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 210,
              "rma_number": "1583217926438",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217926403-2",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:45:26.438Z",
              "updatedAt": "2020-03-03T06:45:26.438Z",
              "productCut": {
                  "id": 175,
                  "product_id": 50,
                  "product_variant_id": 59,
                  "cut_name": "Whole Bird (Without Skin)",
                  "units": "kg",
                  "price_per_unit": 420,
                  "pieces_per_unit": "17",
                  "no_of_serves": "20 - 25",
                  "description": null,
                  "is_default": false,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:20.824Z",
                  "updatedAt": "2020-03-03T04:39:20.824Z",
                  "productVariant": {
                      "id": 59,
                      "product_id": 50,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "PYFRPTK",
                      "total_quantity": 100,
                      "available_quantity": 30,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:16.124Z",
                      "updatedAt": "2020-03-03T04:39:16.124Z",
                      "product": {
                          "id": 50,
                          "sub_category_id": 4,
                          "name": "Turkey",
                          "colloquial_name": null,
                          "code": "PYFRPTK",
                          "min_price": 400,
                          "max_price": 420,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.5,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": true,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.776Z",
                          "updatedAt": "2020-03-03T04:39:15.776Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          },
          {
              "id": 7,
              "product_cut_id": 6,
              "order_id": 8,
              "product_id": 5,
              "product_name": "Japenese Thread Fin Bream",
              "date_placed": "2020-03-03T06:45:26.428Z",
              "item_packed_by": null,
              "order_item_quantity": 0.5,
              "order_item_price": 140,
              "rma_number": "1583217926428",
              "rma_issued_by": null,
              "rma_date": null,
              "barcode": "FFOR1583217926403-1",
              "status": "ACTIVE",
              "createdAt": "2020-03-03T06:45:26.428Z",
              "updatedAt": "2020-03-03T06:45:26.428Z",
              "productCut": {
                  "id": 6,
                  "product_id": 5,
                  "product_variant_id": 5,
                  "cut_name": "Whole Cleaned",
                  "units": "kg",
                  "price_per_unit": 280,
                  "pieces_per_unit": "18",
                  "no_of_serves": "18 - 20",
                  "description": null,
                  "is_default": true,
                  "is_alive": false,
                  "minimum_range": 0.5,
                  "status": "ACTIVE",
                  "createdAt": "2020-03-03T04:39:16.229Z",
                  "updatedAt": "2020-03-03T04:39:16.229Z",
                  "productVariant": {
                      "id": 5,
                      "product_id": 5,
                      "option_id": null,
                      "option_value_id": null,
                      "sku_number": "SFSFHJT",
                      "total_quantity": 100,
                      "available_quantity": 65,
                      "units": "kg",
                      "in_stock": true,
                      "threshold": 30,
                      "lower_threshold": 10,
                      "attributes": null,
                      "description": null,
                      "status": "ACTIVE",
                      "createdAt": "2020-03-03T04:39:15.829Z",
                      "updatedAt": "2020-03-03T04:39:15.829Z",
                      "product": {
                          "id": 5,
                          "sub_category_id": 1,
                          "name": "Japenese Thread Fin Bream",
                          "colloquial_name": "Sankara",
                          "code": "SFSFHJT",
                          "min_price": 280,
                          "max_price": 300,
                          "date": "2020-03-03T04:39:15.035Z",
                          "in_stock": true,
                          "current_rating": 4.5,
                          "is_offer": false,
                          "offer_percentage": 0,
                          "is_fast_selling": false,
                          "attributes": null,
                          "description": null,
                          "status": "ACTIVE",
                          "createdAt": "2020-03-03T04:39:15.104Z",
                          "updatedAt": "2020-03-03T04:39:15.104Z"
                      },
                      "optionValue": null
                  }
              },
              "employee": null
          }
      ],
      "invoice": {
          "id": 3,
          "order_id": 8,
          "user_reward_ref": null,
          "invoice_number": "FFIN1583217926443",
          "invoice_date": "2020-03-02T18:30:00.000Z",
          "invoice_details": "Bought 2 Items from FreshFins",
          "delivery_fee": 0,
          "tax": 17.5,
          "subtotal": 350,
          "promocode": null,
          "discount_amount": 0,
          "total_price": 367.5,
          "mode_of_payment": "CASH",
          "gateway_ref": null,
          "transaction_id": null,
          "is_refund_requested": false,
          "refund_status": null,
          "reason_for_cancellation": null,
          "status": "PENDING",
          "createdAt": "2020-03-03T06:45:26.446Z",
          "updatedAt": "2020-03-03T06:45:26.446Z"
      },
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 5,
      "sequence_number": 5,
      "order_number": "FFOR1583217724225",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:42:04.227Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "4f15",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:42:04.229Z",
      "updatedAt": "2020-03-03T06:42:04.247Z",
      "orderItems": [],
      "invoice": null,
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  },
  {
      "id": 2,
      "sequence_number": 2,
      "order_number": "FFOR1583217348557",
      "customer_ref": 8,
      "date_placed": "2020-03-03T06:35:48.560Z",
      "arrival_date": "2020-03-02T18:30:00.000Z",
      "order_otp": "4d70",
      "shipping_address": "No 3/2 New No 7 Second floor, Kamaraj Ave 1st St, Adyar, Chennai, 600020",
      "shipping_latitude": 13.0017881,
      "shipping_longitude": 80.2530409,
      "shipping_zipcode": null,
      "booking_slot_ref": 2,
      "store_ref": null,
      "is_premium": false,
      "is_feedback_provided": false,
      "is_rating_provided": false,
      "phone_number": "+918220136088",
      "delivery_user_name": "Gajendra E",
      "delivery_phone_number": "+917981581942",
      "supported_area_ref": 2,
      "route_name": null,
      "status": "ACCEPTED",
      "createdAt": "2020-03-03T06:35:48.561Z",
      "updatedAt": "2020-03-03T06:35:48.574Z",
      "orderItems": [],
      "invoice": null,
      "bookingSlot": {
          "id": 2,
          "from_time": "15:00:00",
          "to_time": "18:00:00",
          "code": "EVENING",
          "is_express": false,
          "order_before": 120,
          "description": "Evening",
          "status": "ACTIVE",
          "createdAt": "2020-03-03T04:39:20.911Z",
          "updatedAt": "2020-03-03T04:39:20.911Z"
      },
      "userFeedback": null,
      "store": null
  }
]`

var cars = ['Tesla', 'Nissan', 'Chevy', 'Subaru'];
 
var bala = _.each(cars, function (element, index, list) {
    let output = 'Element: ' + element + ', ' + 'Index: ' + index + ', ' + 'List Length: ' + list.length;
    console.log(JSON.stringify(output))

});

   
}


 render() {
    return (
      <div className="container" >
        <h1>CRUD With Redux  </h1>
        <div className="flex-row">
          {this.state.userAction === "A" ?
            <div className="flex-large">
              <h2>Add user</h2>
              <AddUserForm />    
            </div> :
            <div className="flex-large">
              <h2>Add user</h2>
              <EditUserForm userId={this.state.userId} appScreen={this} />
            </div>}
          <div className="flex-large">
            <h2>View users</h2>     
          <UserTable appScreen={this} />
          </div>
        </div>
      </div>
    );
  }
}

export default App;
